### ISSUE TITLE
kaniko-builder fails because of dockerhub rate limits

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/cc-utils#636]
/kind bug
/priority 1

**What happened**:
Initially kaniko builder was introduced as the solution to the ongoing issues with dockerhub rate limits across the pipelines.

Since 2 days we observe dockerhub rate limits with kaniko builder. These issues block the development and testing of various components.

```
error building image: GET https://index.docker.io/v2/library/golang/manifests/1.16.6: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Traceback (most recent call last):
  File "<string>", line 189, in <module>
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/kaniko/rescued-fs/bin/kaniko', '--no-push', '--dockerfile', 'master-image/Dockerfile', '--context', 'master-image/', '--tarPath', 'apiserver.oci-image.tar', '--destination', 'eu.gcr.io/gardener-project/gardener/apiserver:v1.28.0-dev-aa04ce4c753e3b9fae57d9775001bf8b81c43ab2', '--target', 'apiserver')' returned non-zero exit status 1.
```

Refs:
- https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-master/jobs/master-pull-request-job/builds/1424
- https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-master/jobs/master-pull-request-job/builds/1423.1
- https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-master/jobs/master-pull-request-job/builds/1423
- and many more...

**What you expected to happen**:
No dockerhub rate limits

**Comment by ialidzhikov** [comment]
According to CI/CD folks, the issue is supposed to be fixed by https://github.com/gardener/cc-utils/commit/1b3626b964e5ce58091b7c6d38fce91956d9c83c. Thank you once again for fixing the issue.

Hence I will close this issue for now.

/close
